---
title: "Frank_StatSheet"
author: "Greg"
date: "2023-10-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "/Users/gregorylederer/Desktop/UMass Basketball/Shiny/Reactable Prac")
```

#packages
```{r}
library(gt)
library(gtExtras)
library(gtsummary)
library(dplyr)
library(tidyverse)
```

#data
```{r}
possessions <- 128
data <- read.csv("/Users/gregorylederer/Desktop/UMass Basketball/CodeStatSheet - Sheet1.csv")
save_name <- paste0(format(Sys.Date(), format = "%Y-%m-%d"), ' | Frank Totals.png')
table_subtitle <- paste0(format(Sys.Date(), format="%B %d, %Y"), " | Complete Totals")
```

#fix data
```{r}
data[is.na(data)] = 0

frank <- data %>%
  mutate(
    FG = paste0((Rim_Make+Mid_Make+Three_Make), '/', (Rim_Make+Mid_Make+Three_Make+Rim_Miss+Mid_Miss+Three_Miss)),
    '3P' = paste0((Three_Make), '/', (Three_Make+Three_Miss)),
    ORB = Off_Reb,
    'ORB%' = round((Off_Reb/(Off_Reb+Def_Reb))*100,1),
    DRB = Def_Reb,
    TRB = (Off_Reb+Def_Reb),
    PTS = Pts,
    AST = Ast,
    TO = Tov,
    STL = Stl,
    BLK = Blk
  ) %>%
  select(url, Player, FG, '3P', ORB, 'ORB%', DRB, TRB, PTS, AST, TO, STL, BLK)
frank[is.na(frank)] = 0

total <- c('https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/UMass_Amherst_athletics_logo.svg/1200px-UMass_Amherst_athletics_logo.svg.png',
           "Totals",
           paste0((sum(data$Rim_Make)+sum(data$Mid_Make)+sum(data$Three_Make)), '/', (sum(data$Rim_Make)+sum(data$Mid_Make)+sum(data$Three_Make)+sum(data$Rim_Miss)+sum(data$Mid_Miss)+sum(data$Three_Miss))),
           paste0((sum(data$Three_Make)), '/', (sum(data$Three_Make)+sum(data$Three_Miss))),
           sum(data$Off_Reb),
           round(((sum(data$Off_Reb))/(sum(data$Off_Reb)+sum(data$Def_Reb)))*100,1),
           sum(data$Def_Reb),
           (sum(data$Off_Reb)+sum(data$Def_Reb)),
           sum(data$Pts),
           sum(data$Ast),
           sum(data$Tov),
           sum(data$Stl),
           sum(data$Blk)
           )

frank[nrow(frank)+1,] <- total
```

#footer stuff
```{r}
FG_perc <- as.numeric(round(((sum(data$Rim_Make)+sum(data$Mid_Make)+sum(data$Three_Make))/(sum(data$Rim_Make)+sum(data$Mid_Make)+sum(data$Three_Make)+sum(data$Rim_Miss)+sum(data$Mid_Miss)+sum(data$Three_Miss)))*100,1))
Three_perc <- as.numeric(round(((sum(data$Three_Make))/(sum(data$Three_Make)+sum(data$Three_Miss)))*100,1))
ORB_perc <- as.numeric(round(((sum(data$Off_Reb))/(sum(data$Off_Reb)+sum(data$Def_Reb)))*100,1))
Def_FG_perc <- 100 - FG_perc
```

#make table
```{r}
frank_table <- frank %>%
  gt() %>%
  gt_theme_538() %>%
  gt_highlight_rows(rows = c(2, 4, 6, 8, 10, 12, 14), fill = 'gray94', font_weight = 'normal', font_color = 'gray30') %>%
  gt_highlight_rows(rows = c(16), fill = 'gray77') %>%
  cols_label(url = '', Player = md('**Player**'), FG = md('**FG**'), '3P' = md('**3P**'), ORB = md('**OReb**'), 'ORB%' = md('**OReb%**'), DRB = md('**DReb**'), TRB = md('**TRB**'), PTS = md('**PTS**'), AST = md('**AST**'), TO = md('**TOV**'), STL = md('**STL**'), BLK = md('**BLK**')) %>%
  text_transform(locations = cells_body(vars(url)), fn = function(x) {web_image(url = x, height = px(22.5))}) %>%
  tab_header(title = md('**Practice Stat Sheet**'), subtitle = paste0(table_subtitle)) %>%
  tab_options(table.background.color = 'gray89', heading.background.color = 'gray89', column_labels.background.color = 'gray89') %>%
  tab_options(heading.title.font.size = 30, heading.subtitle.font.size = 15) %>%
  gt_add_divider('3P') %>%
  gt_add_divider(TRB) %>%
  tab_options(column_labels.font.size = 13) %>%
  cols_align(align = c('center'), columns = vars(FG, '3P', ORB, 'ORB%', DRB, TRB, PTS, AST, TO, STL, BLK)) %>%
  tab_source_note(source_note = paste0('FG%: ', FG_perc, '%  |  Def FG%: ', Def_FG_perc, '%  |  3pt%: ', Three_perc, '%  |  Possessions: ', possessions)) %>%
  tab_options(source_notes.font.size = 15) %>%
  gtsave(save_name)
```

