---
title: "Daily Tables"
author: "Greg"
date: "2023-07-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "/Users/gregorylederer/Desktop/UMass Basketball/Shiny/Reactable Prac")
```

#packages
```{r}
library(gt)
library(cowplot)
library(ggpubr)
library(dplyr)
library(gtExtras)
library(shiny)
library(shinythemes)
library(gtsummary)
library(htmltools)
library(paletteer)
library(scales)
library(shinydashboard)
library(shinyjs)
library(ggsci)
library(shinyWidgets)
library(here)
library(rsconnect)
```

#get data and file names
```{r}
possessions <- 128
data <- read.csv("/Users/gregorylederer/Desktop/UMass Basketball/CodeStatSheet - Sheet1.csv")
save_name1 <- paste0(format(Sys.Date(), format = "%Y-%m-%d"), ' | Complete Practice Totals.png')
save_name2 <- paste0(format(Sys.Date(), format = "%Y-%m-%d"), ' | Basic Practice Totals.png')
```

#inputs
```{r}
table_subtitle <- paste0(format(Sys.Date(), format="%B %d, %Y"), " | Complete Totals")
```

#full data
```{r}
data[is.na(data)] = 0

full_practice_data <- data %>%
  mutate(Rim_Per = round(Rim_Make/(Rim_Make+Rim_Miss)*100, 1),
         Mid_Per = round(Mid_Make/(Mid_Make+Mid_Miss)*100, 1),
         Three_Per = round(Three_Make/(Three_Make+Three_Miss)*100,1),
         Rim = paste0(Rim_Make, "/", Rim_Make+Rim_Miss),
         Mid = paste0(Mid_Make, "/", Mid_Make+Mid_Miss),
         Three = paste0(Three_Make, "/", Three_Make+Three_Miss),
         Reb = Off_Reb+Def_Reb,
         ORB_per = round((Off_Reb/(Off_Reb+Def_Reb))*100,1)
         ) %>%
  select(url, Player, Pts, Reb, Ast, Rim, Rim_Per, Mid, Mid_Per, Three, Three_Per, Off_Reb, ORB_per, Def_Reb, Stl, Blk, Tov, Charges, Fouls)

full_practice_data[is.na(full_practice_data)] = 0
```

#full totals row
```{r}
totals_row <- c('https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/UMass_Amherst_athletics_logo.svg/1200px-UMass_Amherst_athletics_logo.svg.png',
                "Totals",
                sum(data$Pts),
                sum(data$Off_Reb)+sum(data$Def_Reb),
                sum(data$Ast),
                paste0(sum(data$Rim_Make), "/", sum(data$Rim_Make)+sum(data$Rim_Miss)),
                round(sum(data$Rim_Make)/(sum(data$Rim_Make)+sum(data$Rim_Miss))*100,1),
                paste0(sum(data$Mid_Make), "/", sum(data$Mid_Make)+sum(data$Mid_Miss)),
                round(sum(data$Mid_Make)/(sum(data$Mid_Make)+sum(data$Mid_Miss))*100,1),
                paste0(sum(data$Three_Make), "/", sum(data$Three_Make)+sum(data$Three_Miss)),
                round(sum(data$Three_Make)/(sum(data$Three_Make)+sum(data$Three_Miss))*100,1),
                sum(data$Off_Reb),
                round((sum(data$Off_Reb)/(sum(data$Off_Reb)+sum(data$Def_Reb)))*100,1),
                sum(data$Def_Reb),
                sum(data$Stl),
                sum(data$Blk),
                sum(data$Tov),
                sum(data$Charges),
                sum(data$Fouls)
                )
full_practice_data[nrow(full_practice_data) + 1,] <- totals_row

full_practice_data$Rim_Per = as.numeric(as.character(full_practice_data$Rim_Per))
full_practice_data$Mid_Per = as.numeric(as.character(full_practice_data$Mid_Per))
full_practice_data$Three_Per = as.numeric(as.character(full_practice_data$Three_Per))

Def_FG. = round(as.numeric((sum(data$Rim_Make)+sum(data$Mid_Make)+sum(data$Three_Make))/(sum(data$Rim_Make)+sum(data$Mid_Make)+sum(data$Three_Make)+sum(data$Rim_Miss)+sum(data$Mid_Miss)+sum(data$Three_Miss)))*100,1)
Def_FG. = 100 - Def_FG.

full_practice_data$poss = NA
full_practice_data$poss[16] = possessions
```

#basic practice data
```{r}
basic_practice_data <- data %>%
  mutate(Two = paste0(Rim_Make+Mid_Make, "/", Rim_Make+Rim_Miss+Mid_Make+Mid_Miss),
         Two_Per = round((Rim_Make+Mid_Make)/(Rim_Make+Rim_Miss+Mid_Make+Mid_Miss)*100,1),
         Reb = Off_Reb+Def_Reb,
         Three_Per = round(Three_Make/(Three_Make+Three_Miss)*100,1),
         Three = paste0(Three_Make, "/", Three_Make+Three_Miss),
         ) %>%
  select(url, Player, Pts, Reb, Ast, Two, Two_Per, Three, Three_Per, Off_Reb, Def_Reb, Stl, Blk, Tov, Fouls)

basic_practice_data[is.na(basic_practice_data)] <- 0
```

#basic totals row
```{r}
totals_row <- c('https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/UMass_Amherst_athletics_logo.svg/1200px-UMass_Amherst_athletics_logo.svg.png', "Totals", 
                sum(basic_practice_data$Pts), 
                sum(data$Off_Reb)+sum(data$Def_Reb), 
                sum(basic_practice_data$Ast), 
                paste0(sum(data$Rim_Make)+sum(data$Mid_Make), "/", sum(data$Rim_Make)+sum(data$Mid_Make)+sum(data$Rim_Miss)+sum(data$Mid_Miss)),
                round((sum(data$Rim_Make)+sum(data$Mid_Make))/(sum(data$Rim_Make)+sum(data$Mid_Make)+sum(data$Rim_Miss)+sum(data$Mid_Miss))*100,1),
                paste0(sum(data$Three_Make), "/", sum(data$Three_Make)+sum(data$Three_Miss)),
                round(sum(data$Three_Make)/(sum(data$Three_Make)+sum(data$Three_Miss))*100,1),
                sum(basic_practice_data$Off_Reb), 
                sum(basic_practice_data$Def_Reb), 
                sum(basic_practice_data$Stl), 
                sum(basic_practice_data$Blk), 
                sum(basic_practice_data$Tov), 
                sum(basic_practice_data$Fouls)
                )
basic_practice_data[nrow(basic_practice_data) + 1,] <- totals_row
```

#full practice table
```{r}
#RColorBrewer::RdYlGn
#ggsci::green_material
full_practice_data <- full_practice_data[,-20:-21]
full_practice_table <- full_practice_data %>%
  gt() %>%
  gt_theme_538() %>%
  gt_highlight_rows(rows = c(2, 4, 6, 8, 10, 12, 14), fill = 'gray94', font_weight = 'normal', font_color = 'gray30') %>%
  gt_highlight_rows(rows = c(16), fill = 'gray77') %>%
  cols_label(url = '', Player = md('**Player**'), Pts = md('**Pts**'), Rim = md('**Rim**'), Rim_Per = md('**Rim%**'), Mid = md('**Mid**'), Mid_Per = md('**Mid%**'), Three = md('**3pt.**'), Three_Per = md('**3pt%**'), Off_Reb = md('**OReb**'), ORB_per = md('**ORB%**'), Def_Reb = md('**DReb**'), Reb = md('**Reb**'), Ast = md('**Ast**'), Stl = md('**Stl**'), Blk = md('**Blk**'), Tov = md('**Tov**'), Charges = md('**Charges**'), Fouls = md('**Fouls**')) %>%
  tab_header(title = md('**Practice Stat Sheet**'), subtitle = paste0(table_subtitle)) %>%
  text_transform(locations = cells_body(vars(url)), fn = function(x) {web_image(url = x, height = px(22.5))}) %>%
  data_color(columns = c(Rim_Per), colors = scales::col_numeric(palette = paletteer::paletteer_d(palette = "RColorBrewer::RdYlGn") %>% as.character(), domain = NULL)) %>%
  data_color(columns = c(Mid_Per), colors = scales::col_numeric(palette = paletteer::paletteer_d(palette = "RColorBrewer::RdYlGn") %>% as.character(), domain = NULL)) %>%
  data_color(columns = c(Three_Per), colors = scales::col_numeric(palette = paletteer::paletteer_d(palette = "RColorBrewer::RdYlGn") %>% as.character(), domain = NULL)) %>%
  tab_options(table.background.color = 'gray89', heading.background.color = 'gray89', column_labels.background.color = 'gray89') %>%
  tab_options(heading.title.font.size = 30, heading.subtitle.font.size = 15) %>%
  gt_add_divider(Ast) %>%
  gt_add_divider(Rim_Per) %>%
  gt_add_divider(Mid_Per) %>%
  gt_add_divider(Three_Per) %>%
  tab_options(column_labels.font.size = 13) %>%
  cols_align(align = c('center'), columns = vars(Pts, Reb, Ast, Rim, Rim_Per, Mid, Mid_Per, Three, Three_Per, Off_Reb, ORB_per, Def_Reb, Stl, Blk, Tov, Charges, Fouls)) %>%
  tab_source_note(source_note = paste0('Def FG%: ', Def_FG., '% | Possessions: ', possessions)) %>%
  tab_options(source_notes.font.size = 15) %>%
  gtsave(save_name1)
```

#basic practice table
```{r}
basic_practice_table <- basic_practice_data %>%
  gt() %>%
  gt_theme_538() %>%
  gt_highlight_rows(rows = c(2, 4, 6, 8, 10, 12, 14), fill = 'gray94', font_weight = 'normal', font_color = 'gray30') %>%
  gt_highlight_rows(rows = c(16), fill = 'gray77') %>%
  cols_label(url = '', Player = md('**Player**'), Pts = md('**Pts**'), Two = md('**2pt.**'), Two_Per = md('**2pt%**'), Three = md('**3pt.**'), Three_Per = md('**3pt%**'), Off_Reb = md('**OReb**'), Def_Reb = md('**DReb**'), Reb = md('**Reb**'), Ast = md('**Ast**'), Stl = md('**Stl**'), Blk = md('**Blk**'), Tov = md('**Tov**'), Fouls = md('**Fouls**')) %>%
  tab_header(title = md('**Practice Stat Sheet**'), subtitle = table_subtitle) %>%
  text_transform(locations = cells_body(vars(url)), fn = function(x) {web_image(url = x, height = px(22.5))}) %>%
  tab_options(table.background.color = 'gray89', heading.background.color = 'gray89', column_labels.background.color = 'gray89') %>%
  tab_options(heading.title.font.size = 30, heading.subtitle.font.size = 15) %>%
  cols_align(align = c('center'), columns = vars(Pts, Two, Two_Per, Three, Three_Per, Off_Reb, Def_Reb, Reb, Ast, Stl, Blk, Tov, Fouls)) %>%
  gt_add_divider(Ast) %>%
  gt_add_divider(Two_Per) %>%
  gt_add_divider(Three_Per) %>%
  tab_source_note(source_note = paste0('Possessions: ', possessions)) %>%
  tab_options(source_notes.font.size = 15) %>%
  gtsave(save_name2)
```

