---
title: "Weekly Tables"
author: "Greg"
date: "2023-07-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "/Users/gregorylederer/Desktop/UMass Basketball/Shiny/Reactable Prac")
```

#library
```{r}
library(gt)
library(cowplot)
library(ggpubr)
library(dplyr)
library(gtExtras)
```

#input
```{r}
week <- '11.20 - 11.26' #monday to sunday

table_subtitle1 <- paste0(week, " | Complete Totals")
table_subtitle2 <- paste0(week, " | Basic Totals")
table_subtitle3 <- paste0(week, " | Advanced Totals")
save_name1 <- paste0(week, " - Complete Totals Stat Sheet.png")
save_name2 <- paste0(week, " - Basic Totals Stat Sheet.png")
save_name3 <- paste0(week, " - Advanced Totals Stat Sheet.png")
```

#read data
```{r}
practice_data <- read.csv('/Users/gregorylederer/Desktop/UMass Basketball/23-24 Practice Stat Sheet - Weekly Totals.csv')
urls <- c('https://images.sidearmdev.com/crop?url=https%3A%2F%2Fdxbhsrqyrr690.cloudfront.net%2Fsidearm.nextgen.sites%2Fumassathletics.com%2Fimages%2F2023%2F10%2F10%2FRollie_Castineyra_CgC7L.jpg&width=100&height=100&gravity=north&type=webp',
          'https://images.sidearmdev.com/crop?url=https%3A%2F%2Fdxbhsrqyrr690.cloudfront.net%2Fsidearm.nextgen.sites%2Fumassathletics.com%2Fimages%2F2023%2F10%2F10%2FJosh_MYSjy.jpg&width=100&height=100&gravity=north&type=webp',
          'https://images.sidearmdev.com/crop?url=https%3A%2F%2Fdxbhsrqyrr690.cloudfront.net%2Fsidearm.nextgen.sites%2Fumassathletics.com%2Fimages%2F2023%2F10%2F10%2FJackson_Cronin_SdErY.jpg&width=100&height=100&gravity=north&type=webp',
          'https://images.sidearmdev.com/crop?url=https%3A%2F%2Fdxbhsrqyrr690.cloudfront.net%2Fsidearm.nextgen.sites%2Fumassathletics.com%2Fimages%2F2023%2F10%2F10%2FMatt_q1H5m.jpg&width=100&height=100&gravity=north&type=webp',
          'https://images.sidearmdev.com/crop?url=https%3A%2F%2Fdxbhsrqyrr690.cloudfront.net%2Fsidearm.nextgen.sites%2Fumassathletics.com%2Fimages%2F2023%2F10%2F10%2FJaylen_HWhjg.jpg&width=100&height=100&gravity=north&type=webp',
          'https://images.sidearmdev.com/crop?url=https%3A%2F%2Fdxbhsrqyrr690.cloudfront.net%2Fsidearm.nextgen.sites%2Fumassathletics.com%2Fimages%2F2023%2F10%2F10%2FRobert_F5SIh.jpg&width=100&height=100&gravity=north&type=webp',
          'https://images.sidearmdev.com/crop?url=https%3A%2F%2Fdxbhsrqyrr690.cloudfront.net%2Fsidearm.nextgen.sites%2Fumassathletics.com%2Fimages%2F2023%2F10%2F10%2FRahsool_Diggins_nOrSz.jpg&width=100&height=100&gravity=north&type=webp',
          'https://images.sidearmdev.com/crop?url=https%3A%2F%2Fdxbhsrqyrr690.cloudfront.net%2Fsidearm.nextgen.sites%2Fumassathletics.com%2Fimages%2F2023%2F10%2F10%2FTarique_Foster_JV3ru.jpg&width=100&height=100&gravity=north&type=webp',
          'https://images.sidearmdev.com/crop?url=https%3A%2F%2Fdxbhsrqyrr690.cloudfront.net%2Fsidearm.nextgen.sites%2Fumassathletics.com%2Fimages%2F2023%2F10%2F10%2FDaniel_Hankins_Sanford_d3tPh.jpg&width=100&height=100&gravity=north&type=webp',
          'https://images.sidearmdev.com/crop?url=https%3A%2F%2Fdxbhsrqyrr690.cloudfront.net%2Fsidearm.nextgen.sites%2Fumassathletics.com%2Fimages%2F2023%2F10%2F10%2FMathok_PYwqm.jpg&width=100&height=100&gravity=north&type=webp',
          'https://images.sidearmdev.com/crop?url=https%3A%2F%2Fdxbhsrqyrr690.cloudfront.net%2Fsidearm.nextgen.sites%2Fumassathletics.com%2Fimages%2F2023%2F10%2F10%2FRyan_Marcus_zHwGy.jpg&width=100&height=100&gravity=north&type=webp',
          'https://images.sidearmdev.com/crop?url=https://dxbhsrqyrr690.cloudfront.net/sidearm.nextgen.sites/umassathletics.com/images/2023/5/18/Mayhugh_Sawyer.jpg&width=100&height=100&gravity=north&type=webp',
          'https://images.sidearmdev.com/crop?url=https%3A%2F%2Fdxbhsrqyrr690.cloudfront.net%2Fsidearm.nextgen.sites%2Fumassathletics.com%2Fimages%2F2023%2F10%2F10%2FJayden_Ndjigue_uDraA.jpg&width=100&height=100&gravity=north&type=webp',
          'https://images.sidearmdev.com/crop?url=https%3A%2F%2Fdxbhsrqyrr690.cloudfront.net%2Fsidearm.nextgen.sites%2Fumassathletics.com%2Fimages%2F2023%2F10%2F10%2FKeon_Thompson_j7lVX.jpg&width=100&height=100&gravity=north&type=webp',
          'https://images.sidearmdev.com/crop?url=https%3A%2F%2Fdxbhsrqyrr690.cloudfront.net%2Fsidearm.nextgen.sites%2Fumassathletics.com%2Fimages%2F2023%2F10%2F10%2FMarqui_Worthy_fB7nD.jpg&width=100&height=100&gravity=north&type=webp',
          'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/UMass_Amherst_athletics_logo.svg/1200px-UMass_Amherst_athletics_logo.svg.png')
```

#fix data
```{r}
possessions <- as.numeric(practice_data$X.1[19])

practice_data <- practice_data[-(17:32),]
practice_data <- practice_data[-1,]

colnames(practice_data)[1] = 'Player'
colnames(practice_data)[2] = 'Pts'
colnames(practice_data)[3] = 'Rim_Make'
colnames(practice_data)[4] = 'Rim_Miss'
colnames(practice_data)[5] = 'Mid_Make'
colnames(practice_data)[6] = 'Mid_Miss'
colnames(practice_data)[7] = 'Three_Make'
colnames(practice_data)[8] = 'Three_Miss'
colnames(practice_data)[9] = 'Off_Reb'
colnames(practice_data)[10] = 'Def_Reb'
colnames(practice_data)[11] = 'Ast'
colnames(practice_data)[12] = 'Stl'
colnames(practice_data)[13] = 'Blk'
colnames(practice_data)[14] = 'Tov'
colnames(practice_data)[15] = 'Charges'
colnames(practice_data)[16] = 'Fouls'

practice_data$Pts <- as.numeric(practice_data$Pts)
practice_data$Rim_Make <- as.numeric(practice_data$Rim_Make)
practice_data$Rim_Miss <- as.numeric(practice_data$Rim_Miss)
practice_data$Mid_Make <- as.numeric(practice_data$Mid_Make)
practice_data$Mid_Miss <- as.numeric(practice_data$Mid_Miss)
practice_data$Three_Make <- as.numeric(practice_data$Three_Make)
practice_data$Three_Miss <- as.numeric(practice_data$Three_Miss)
practice_data$Off_Reb <- as.numeric(practice_data$Off_Reb)
practice_data$Def_Reb <- as.numeric(practice_data$Def_Reb)
practice_data$Ast <- as.numeric(practice_data$Ast)
practice_data$Stl <- as.numeric(practice_data$Stl)
practice_data$Blk <- as.numeric(practice_data$Blk)
practice_data$Tov <- as.numeric(practice_data$Tov)
practice_data$Charges <- as.numeric(practice_data$Charges)
practice_data$Fouls <- as.numeric(practice_data$Fouls)

Def_FG. = round(as.numeric((sum(practice_data$Rim_Make)+sum(practice_data$Mid_Make)+sum(practice_data$Three_Make))/(sum(practice_data$Rim_Make)+sum(practice_data$Mid_Make)+sum(practice_data$Three_Make)+sum(practice_data$Rim_Miss)+sum(practice_data$Mid_Miss)+sum(practice_data$Three_Miss)))*100,1)
Def_FG. = 100 - Def_FG.
```

#full data
```{r}
practice_data[is.na(practice_data)] = 0

full_practice_data <- practice_data %>%
  mutate(Rim_Per = round(Rim_Make/(Rim_Make+Rim_Miss)*100, 1),
         Mid_Per = round(Mid_Make/(Mid_Make+Mid_Miss)*100, 1),
         Three_Per = round(Three_Make/(Three_Make+Three_Miss)*100,1),
         Rim = paste0(Rim_Make, "/", Rim_Make+Rim_Miss),
         Mid = paste0(Mid_Make, "/", Mid_Make+Mid_Miss),
         Three = paste0(Three_Make, "/", Three_Make+Three_Miss),
         Reb = Off_Reb+Def_Reb,
         ORB_per = round((Off_Reb/(Off_Reb+Def_Reb))*100,1)
         ) %>%
  select(Player, Pts, Reb, Ast, Rim, Rim_Per, Mid, Mid_Per, Three, Three_Per, Off_Reb, ORB_per, Def_Reb, Stl, Blk, Tov, Charges, Fouls) 

full_practice_data[is.na(full_practice_data)] = 0
```

#full totals row
```{r}
full_totals_row <- c(
                "Totals",
                sum(practice_data$Pts),
                sum(practice_data$Off_Reb)+sum(practice_data$Def_Reb),
                sum(practice_data$Ast),
                paste0(sum(practice_data$Rim_Make), "/", sum(practice_data$Rim_Make)+sum(practice_data$Rim_Miss)),
                round(sum(practice_data$Rim_Make)/(sum(practice_data$Rim_Make)+sum(practice_data$Rim_Miss))*100,1),
                paste0(sum(practice_data$Mid_Make), "/", sum(practice_data$Mid_Make)+sum(practice_data$Mid_Miss)),
                round(sum(practice_data$Mid_Make)/(sum(practice_data$Mid_Make)+sum(practice_data$Mid_Miss))*100,1),
                paste0(sum(practice_data$Three_Make), "/", sum(practice_data$Three_Make)+sum(practice_data$Three_Miss)),
                round(sum(practice_data$Three_Make)/(sum(practice_data$Three_Make)+sum(practice_data$Three_Miss))*100,1),
                sum(practice_data$Off_Reb),
                round((sum(practice_data$Off_Reb)/(sum(practice_data$Off_Reb)+sum(practice_data$Def_Reb)))*100,1),
                sum(practice_data$Def_Reb),
                sum(practice_data$Stl),
                sum(practice_data$Blk),
                sum(practice_data$Tov),
                sum(practice_data$Charges),
                sum(practice_data$Fouls)
                )
full_practice_data[nrow(full_practice_data) + 1,] <- full_totals_row

full_practice_data$Rim_Per = as.numeric(as.character(full_practice_data$Rim_Per))
full_practice_data$Mid_Per = as.numeric(as.character(full_practice_data$Mid_Per))
full_practice_data$Three_Per = as.numeric(as.character(full_practice_data$Three_Per))
```

#basic practice data
```{r}
basic_practice_data <- practice_data %>%
  mutate(Two = paste0(Rim_Make+Mid_Make, "/", Rim_Make+Rim_Miss+Mid_Make+Mid_Miss),
         Two_Per = round((Rim_Make+Mid_Make)/(Rim_Make+Rim_Miss+Mid_Make+Mid_Miss)*100,1),
         Reb = Off_Reb+Def_Reb,
         Three_Per = round(Three_Make/(Three_Make+Three_Miss)*100,1),
         Three = paste0(Three_Make, "/", Three_Make+Three_Miss)
         ) %>%
  select(Player, Pts, Reb, Ast, Two, Two_Per, Three, Three_Per, Off_Reb, Def_Reb, Stl, Blk, Tov, Fouls)

basic_practice_data[is.na(basic_practice_data)] <- 0
```

#basic totals row
```{r}
basic_totals_row <- c("Totals", 
                sum(basic_practice_data$Pts), 
                sum(practice_data$Off_Reb)+sum(practice_data$Def_Reb), 
                sum(basic_practice_data$Ast), 
                paste0(sum(practice_data$Rim_Make)+sum(practice_data$Mid_Make), "/", sum(practice_data$Rim_Make)+sum(practice_data$Mid_Make)+sum(practice_data$Rim_Miss)+sum(practice_data$Mid_Miss)),
                round((sum(practice_data$Rim_Make)+sum(practice_data$Mid_Make))/(sum(practice_data$Rim_Make)+sum(practice_data$Mid_Make)+sum(practice_data$Rim_Miss)+sum(practice_data$Mid_Miss))*100,1),
                paste0(sum(practice_data$Three_Make), "/", sum(practice_data$Three_Make)+sum(practice_data$Three_Miss)),
                round(sum(practice_data$Three_Make)/(sum(practice_data$Three_Make)+sum(practice_data$Three_Miss))*100,1),
                sum(basic_practice_data$Off_Reb), 
                sum(basic_practice_data$Def_Reb), 
                sum(basic_practice_data$Stl), 
                sum(basic_practice_data$Blk), 
                sum(basic_practice_data$Tov), 
                sum(basic_practice_data$Fouls)
                )
basic_practice_data[nrow(basic_practice_data) + 1,] <- basic_totals_row
```

#advanced data
```{r}
advanced_data <- practice_data %>%
  mutate(Rim_par = round(((Rim_Make+Rim_Miss)/(Rim_Make+Rim_Miss+Mid_Make+Mid_Miss+Three_Make+Three_Miss))*100, 1),
         Mid_par = round(((Mid_Make+Mid_Miss)/(Rim_Make+Rim_Miss+Mid_Make+Mid_Miss+Three_Make+Three_Miss))*100, 1),
         Three_par = round(((Three_Make+Three_Miss)/(Rim_Make+Rim_Miss+Mid_Make+Mid_Miss+Three_Make+Three_Miss))*100, 1),
         eFG = round((((Rim_Make+Mid_Make+Three_Make)+(0.5*Three_Make))/(Rim_Make+Rim_Miss+Mid_Make+Mid_Miss+Three_Make+Three_Miss))*100,1),
         Rim = paste0(Rim_Make, "/", Rim_Make+Rim_Miss),
         Mid = paste0(Mid_Make, "/", Mid_Make+Mid_Miss),
         Three = paste0(Three_Make, "/", Three_Make+Three_Miss),
         Rim_Per = round(Rim_Make/(Rim_Make+Rim_Miss)*100, 1),
         Mid_Per = round(Mid_Make/(Mid_Make+Mid_Miss)*100, 1),
         Three_Per = round(Three_Make/(Three_Make+Three_Miss)*100,1)
         ) %>%
  select(Player, Pts, eFG, Rim, Rim_Per, Rim_par, Mid, Mid_Per, Mid_par, Three, Three_Per, Three_par)
advanced_data[is.na(advanced_data)] <- 0
```

#advanced total row
```{r}
advanced_totals_row <- c("Totals", 
                sum(practice_data$Pts), 
                round((((sum(practice_data$Rim_Make)+sum(practice_data$Mid_Make)+sum(practice_data$Three_Make))+(0.5*sum(practice_data$Three_Make)))/(sum(practice_data$Rim_Make)+sum(practice_data$Rim_Miss)+sum(practice_data$Mid_Make)+sum(practice_data$Mid_Miss)+sum(practice_data$Three_Make)+sum(practice_data$Three_Miss)))*100,1),
                paste0(sum(practice_data$Rim_Make), "/", sum(practice_data$Rim_Make)+sum(practice_data$Rim_Miss)),
                round(sum(practice_data$Rim_Make)/(sum(practice_data$Rim_Make)+sum(practice_data$Rim_Miss))*100,1),
                round(((sum(practice_data$Rim_Make)+sum(practice_data$Rim_Miss))/(sum(practice_data$Rim_Make)+sum(practice_data$Rim_Miss)+sum(practice_data$Mid_Make)+sum(practice_data$Mid_Miss)+sum(practice_data$Three_Make)+sum(practice_data$Three_Miss)))*100,1),
                paste0(sum(practice_data$Mid_Make), "/", sum(practice_data$Mid_Make)+sum(practice_data$Mid_Miss)),
                round(sum(practice_data$Mid_Make)/(sum(practice_data$Mid_Make)+sum(practice_data$Mid_Miss))*100,1),
                round(((sum(practice_data$Mid_Make)+sum(practice_data$Mid_Miss))/(sum(practice_data$Rim_Make)+sum(practice_data$Rim_Miss)+sum(practice_data$Mid_Make)+sum(practice_data$Mid_Miss)+sum(practice_data$Three_Make)+sum(practice_data$Three_Miss)))*100,1),
                paste0(sum(practice_data$Three_Make), "/", sum(practice_data$Three_Make)+sum(practice_data$Three_Miss)),
                round(sum(practice_data$Three_Make)/(sum(practice_data$Three_Make)+sum(practice_data$Three_Miss))*100,1),
                round(((sum(practice_data$Three_Make)+sum(practice_data$Three_Miss))/(sum(practice_data$Rim_Make)+sum(practice_data$Rim_Miss)+sum(practice_data$Mid_Make)+sum(practice_data$Mid_Miss)+sum(practice_data$Three_Make)+sum(practice_data$Three_Miss)))*100,1))

advanced_data[nrow(advanced_data) + 1,] <- advanced_totals_row

advanced_data$eFG = as.numeric(as.character(advanced_data$eFG))
```

#add urls
```{r}
full_practice_data <- cbind(urls, full_practice_data)
basic_practice_data <- cbind(urls, basic_practice_data)
advanced_data <- cbind(urls, advanced_data)
```

#full practice table
```{r}
#RColorBrewer::RdYlGn
#ggsci::green_material
full_practice_table <- full_practice_data %>%
  gt() %>%
  gt_theme_538() %>%
  gt_highlight_rows(rows = c(2, 4, 6, 8, 10, 12, 14), fill = 'gray78', font_weight = 'normal', font_color = 'gray30') %>%
  gt_highlight_rows(rows = c(16), fill = 'gray67') %>%
  cols_label(urls = '', Player = md('**Player**'), Pts = md('**Pts**'), Rim = md('**Rim**'), Rim_Per = md('**Rim%**'), Mid = md('**Mid**'), Mid_Per = md('**Mid%**'), Three = md('**3pt.**'), Three_Per = md('**3pt%**'), Off_Reb = md('**OReb**'), ORB_per = md('**ORB%**'), Def_Reb = md('**DReb**'), Reb = md('**Reb**'), Ast = md('**Ast**'), Stl = md('**Stl**'), Blk = md('**Blk**'), Tov = md('**Tov**'), Charges = md('**Charges**'), Fouls = md('**Fouls**')) %>%
  tab_header(title = md('**Practice Stat Sheet**'), subtitle = table_subtitle1) %>%
  text_transform(locations = cells_body(vars(urls)), fn = function(x) {web_image(url = x, height = px(22.5))}) %>%
  data_color(columns = c(Rim_Per), colors = scales::col_numeric(palette = paletteer::paletteer_d(palette = "RColorBrewer::RdYlGn") %>% as.character(), domain = NULL)) %>%
  data_color(columns = c(Mid_Per), colors = scales::col_numeric(palette = paletteer::paletteer_d(palette = "RColorBrewer::RdYlGn") %>% as.character(), domain = NULL)) %>%
  data_color(columns = c(Three_Per), colors = scales::col_numeric(palette = paletteer::paletteer_d(palette = "RColorBrewer::RdYlGn") %>% as.character(), domain = NULL)) %>%
  tab_options(table.background.color = 'gray89', heading.background.color = 'gray89', column_labels.background.color = 'gray89') %>%
  tab_options(heading.title.font.size = 30, heading.subtitle.font.size = 15) %>%
  gt_add_divider(Ast) %>%
  gt_add_divider(Rim_Per) %>%
  gt_add_divider(Mid_Per) %>%
  gt_add_divider(Three_Per) %>%
  tab_options(column_labels.font.size = 13) %>%
  cols_align(align = c('center'), columns = vars(Pts, Reb, Ast, Rim, Rim_Per, Mid, Mid_Per, Three, Three_Per, Off_Reb, ORB_per, Def_Reb, Stl, Blk, Tov, Charges, Fouls)) %>%
  tab_source_note(source_note = paste0('Def FG%: ', Def_FG., '% | Possessions: ', possessions)) %>%
  tab_options(source_notes.font.size = 15) %>%
  gtsave(save_name1)
full_practice_table
```

#basic practice table
```{r}
basic_practice_table <- basic_practice_data %>%
  gt() %>%
  gt_theme_538() %>%
  gt_highlight_rows(rows = c(2, 4, 6, 8, 10, 12, 14), fill = 'gray78', font_weight = 'normal', font_color = 'gray30') %>%
  gt_highlight_rows(rows = c(16), fill = 'gray67') %>%
  cols_label(urls = '', Player = md('**Player**'), Pts = md('**Pts**'), Two = md('**2pt.**'), Two_Per = md('**2pt%**'), Three = md('**3pt.**'), Three_Per = md('**3pt%**'), Off_Reb = md('**OReb**'), Def_Reb = md('**DReb**'), Reb = md('**Reb**'), Ast = md('**Ast**'), Stl = md('**Stl**'), Blk = md('**Blk**'), Tov = md('**Tov**'), Fouls = md('**Fouls**')) %>%
  tab_header(title = md('**Practice Stat Sheet**'), subtitle = table_subtitle2) %>%
  text_transform(locations = cells_body(vars(urls)), fn = function(x) {web_image(url = x, height = px(22.5))}) %>%
  tab_options(table.background.color = 'gray89', heading.background.color = 'gray89', column_labels.background.color = 'gray89') %>%
  tab_options(heading.title.font.size = 30, heading.subtitle.font.size = 15) %>%
  cols_align(align = c('center'), columns = vars(Pts, Two, Two_Per, Three, Three_Per, Off_Reb, Def_Reb, Reb, Ast, Stl, Blk, Tov, Fouls)) %>%
  gt_add_divider(Ast) %>%
  gt_add_divider(Two_Per) %>%
  gt_add_divider(Three_Per) %>%
  tab_source_note(source_note = paste0('Possessions: ', possessions)) %>%
  tab_options(source_notes.font.size = 15) %>%
  gtsave(save_name2)
```

#advanced table
```{r}
advanced_table <- advanced_data %>%
  gt() %>%
  gt_theme_538() %>%
  gt_highlight_rows(rows = c(2, 4, 6, 8, 10, 12, 14), fill = 'gray78', font_weight = 'normal', font_color = 'gray30') %>%
  gt_highlight_rows(rows = c(16), fill = 'gray67') %>%
  cols_label(urls = '', Player = md('**Player**'), Pts = md('**Pts**'), eFG = md('**eFG%**'), Rim = md('**Rim**'), Rim_Per = md('**Rim%**'), Rim_par = md('**Att. Rate**'), Mid = md('**Mid**'), Mid_Per = md('**Mid%**'), Mid_par = md('**Att. Rate**'), Three = md('**Three**'), Three_Per = md('**3pt%**'), Three_par = md('**Att. Rate**')) %>%
  tab_header(title = md('**Advanced Stat Sheet**'), subtitle = table_subtitle3) %>%
  text_transform(locations = cells_body(vars(urls)), fn = function(x) {web_image(url = x, height = px(22.5))}) %>%
  tab_options(table.background.color = 'gray89', heading.background.color = 'gray89', column_labels.background.color = 'gray89') %>%
  tab_options(heading.title.font.size = 30, heading.subtitle.font.size = 15) %>%
  gt_add_divider(eFG) %>%
  gt_add_divider(Rim_par) %>%
  gt_add_divider(Mid_par) %>%
  tab_source_note(source_note = md('*Att. Rate - shots per 100 FGA*')) %>%
  cols_align(align = c('center'), columns = vars(Pts, eFG, Rim, Rim_Per, Rim_par, Mid, Mid_Per, Mid_par, Three, Three_Per, Three_par)) %>%
  data_color(columns = c(eFG), colors = scales::col_numeric(palette = paletteer::paletteer_d(palette = "RColorBrewer::RdYlGn") %>% as.character(), domain = NULL)) %>%
  tab_source_note(source_note = paste0('Def FG%: ', Def_FG., '% | Possessions: ', possessions)) %>%
  tab_options(source_notes.font.size = 15) %>%
  gtsave(save_name3)
```
